"""
Task 2.1 helper — Convert URDF → MJCF and write scene/world.xml.

Run once from VLATraining/sim/:
    python -m scene.build_world

Produces:
    assets/mjcf/kr6r900sixx.xml  ← robot-only MJCF (no ground/lights)
    scene/world.xml              ← full scene MJCF (robot + ground + lights + sky)
"""
import os
import mujoco

# ── Paths ──────────────────────────────────────────────────────────────────
SIM_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URDF_PATH = os.path.join(SIM_DIR, "assets", "urdf", "kr6r900sixx.urdf")
MJCF_DIR  = os.path.join(SIM_DIR, "assets", "mjcf")
MJCF_PATH = os.path.join(MJCF_DIR, "kr6r900sixx.xml")
WORLD_PATH = os.path.join(SIM_DIR, "scene", "world.xml")

os.makedirs(MJCF_DIR, exist_ok=True)

# ── Step 1: load URDF and save as MJCF ────────────────────────────────────
print(f"Loading URDF: {URDF_PATH}")
model = mujoco.MjModel.from_xml_path(URDF_PATH)
print(f"  nq={model.nq}, nbody={model.nbody}")

# mj_saveLastXML saves the last model compiled from XML
err_buf = mujoco.mj_saveLastXML(MJCF_PATH, model)
if err_buf:
    raise RuntimeError(f"mj_saveLastXML error: {err_buf}")
print(f"Saved robot MJCF: {MJCF_PATH}")

# ── Step 2: write scene/world.xml ─────────────────────────────────────────
# Paths are relative to scene/world.xml
rel_mjcf = os.path.relpath(MJCF_PATH, os.path.dirname(WORLD_PATH))
rel_mjcf = rel_mjcf.replace("\\", "/")   # Windows safety

WORLD_XML = f"""\
<mujoco model="kuka_scene">

  <!--
    Task 2.1 — World scene: ground plane, lighting, sky, KUKA KR6 R900 sixx arm.
    Generated by scene/build_world.py — do not edit meshdir paths manually.
  -->

  <!-- Robot (converted from URDF) -->
  <include file="{rel_mjcf}"/>

  <!-- Sky colour: neutral light blue -->
  <visual>
    <global offwidth="1280" offheight="720"/>
    <rgba skyrgb=".2 .31 .43"/>
  </visual>

  <worldbody>

    <!-- Ground plane: 10 m × 10 m, grey -->
    <geom name="floor"
          type="plane"
          size="5 5 0.1"
          rgba="0.55 0.55 0.55 1"
          condim="3"/>

    <!-- Main overhead directional light -->
    <light name="top"
           pos="0 0 4"
           dir="0 0 -1"
           diffuse="0.9 0.9 0.9"
           specular="0.3 0.3 0.3"
           directional="true"
           castshadow="true"/>

    <!-- Fill light from front-left to reduce harsh shadows -->
    <light name="fill"
           pos="2 -2 3"
           dir="-0.5 0.5 -1"
           diffuse="0.45 0.45 0.45"
           specular="0 0 0"
           directional="true"
           castshadow="false"/>

  </worldbody>

</mujoco>
"""

with open(WORLD_PATH, "w") as f:
    f.write(WORLD_XML)
print(f"Wrote: {WORLD_PATH}")

# ── Step 3: quick smoke test ───────────────────────────────────────────────
print("\nSmoke test: loading scene/world.xml ...")
scene_model = mujoco.MjModel.from_xml_path(WORLD_PATH)
print(f"  nq={scene_model.nq}, nbody={scene_model.nbody}  ✓")
